apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: test-annotations-yeql
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-annotations-yeql
    app.kubernetes.io/part-of: test-annotations-app-eadr
  name: test-annotations-yeql
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: my-nginx
      app.kubernetes.io/instance: test-annotations-yeql
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: my-nginx
        app.kubernetes.io/instance: test-annotations-yeql
    spec:
      containers:
      - image: quay.io/tnevrlka-test/build-e2e-hitv-tenant/test-annotations-app-eadr/test-annotations-yeql@sha256:9dc184ac2782c750b9905ace12ce7e2db9bbab95239797ee3cf417f1e1ce2655
        name: my-nginx
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 8081
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
